kevin-lee/sbt-devoops

- src/main/scala/io/kevinlee/sbt/devoops/DevOopsJavaPlugin.scala
Summary
=======
Close #15 - Plugin to support Java projects
***
Added:
------
- `DevOopsJavaPlugin` for Java project
- `javaVersion` setting
- set `crossPaths` and `autoScalaLibrary` to false
- default `javacOptions`: `-source` and `-target` set to the `javaVersion` above, `-Xlint:unchecked`, and set `-encoding` to `UTF-8`
> Task #15 - Plugin to support Java projects

- src/main/scala/io/kevinlee/git/Git.scala
- src/main/scala/io/kevinlee/git/GitCommandError.scala
- src/main/scala/io/kevinlee/git/GitCommandResult.scala
- src/main/scala/io/kevinlee/git/sysProcess.scala
- src/main/scala/io/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
- src/main/scala/io/kevinlee/sbt/devoops/data/SbtTask.scala
- src/main/scala/io/kevinlee/sbt/devoops/data/SbtTaskError.scala
- src/main/scala/io/kevinlee/sbt/devoops/data/SbtTaskResult.scala
Summary
=======
Task #23 - Tag when merge into release branch happens (work in progress)
* a method to run generic git commands
* git fetch --tags before tagging
* result and error message
* Now the git command results are accumulated (the first error causes the failure just like before)
> git fetch tags and other git command helpers

- src/main/scala/io/kevinlee/git/Git.scala
- src/main/scala/io/kevinlee/git/GitCommandResult.scala
- src/main/scala/io/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Summary
=======
Task #23 - Tag when merge into release branch happens (work in progress)
* gitTag properly accumulate each result
```
sbt:test-project> gitTag
task success> git commands
>> git rev-parse --abbrev-ref HEAD (current branch name: release)
>> git current branch name is equal to the given one. current: release
>> git fetch --tags
>> git tag v0.1.0-SNAPSHOT
```
```
sbt:test-project> gitTag
[error] java.lang.RuntimeException: Unexpected git command result
[error] expected: current branch == given expected branch. expected: release
[error] ---
[error]   actual: git rev-parse --abbrev-ref HEAD (current branch name: master)
...
```
> Task #23 - Tag when merge into release branch happens (work in progress)

- src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
* Changed: `gitTagDescription` is optional now (default: `None`)
> Make `gitTagDescription` optional

- README.md
Summary
=======
Changed: README.md
* removed resolver from 'Get sbt-devoops' as it's no longer needed. This project repo in bintray is connected to sbt's.
> Changed: README.md

- README.md
- src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Summary
=======
Close #63 - Change the default gitTagFrom branch from release to master
> Close #63 - Change the default gitTagFrom branch from release to master

- src/main/scala/kevinlee/github/data/github.scala
- src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Added: more types for `runGitHubRelease` method to make it safer
> Added: more types for runGitHubRelease method to make it safer

- src/main/scala/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala
Close #99 - Remove `-Ywarn-numeric-widen` from Scala 2.10 config
> Close #99 - Remove -Ywarn-numeric-widen from Scala 2.10 config

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
- changelogs/1.0.3.md
- project/ProjectInfo.scala
* Replace `SemanticVersion` with `just-semver` lib (#105)
* Upgrade sbt for building `sbt-devoops` (#111)
* Add `partial-unification` to `scalacOptions` (#117)
* Upgrade sbt to `1.3.3` (#107)
* Upgrade sbt to `1.3.4` (#119)
* Remove `javacOptions` causing problems (#113)
> sbt-devoops v1.0.3

- website/docusaurus.config.js
- website/sidebars.js
- website/src/css/custom.css
* The container max width: 1140px => 1240px
* `gh-release-plugin` pages in the sidebar are not collapsed by default
* Change and fix in labeling and path
> Changed: doc site config

- src/main/scala/kevinlee/git/Git.scala
- src/main/scala/kevinlee/github/OldGitHubApi.scala
- src/main/scala/kevinlee/github/data/GitHubError.scala
- src/main/scala/kevinlee/github/data/github.scala
Issue #146 - Some changes in existing types including errors
> Issue #146 - Some changes in existing types including errors

- src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Close #167 - Change the default branch for `gitTagFrom` from mater to main
> Close #167 - Change the default branch for gitTagFrom from mater to main

- src/main/scala/kevinlee/github/GitHubApi.scala
- src/main/scala/kevinlee/github/data/GitHub.scala
- src/main/scala/kevinlee/http/HttpError.scala
Issue #181 - Added: A function to get all tags to `GitHubApi`
> Issue #181 - Added: A function to get all tags to GitHubApi

- src/main/scala/kevinlee/sbt/devoops/DevOopsGitHubReleasePlugin.scala
Issue #187 - Change `DevOopsGitReleasePlugin` to `DevOopsGitHubReleasePlugin`
> Issue #187 - Change DevOopsGitReleasePlugin to DevOopsGitHubReleasePlugin

- .github/workflows/manual-publish-github-pages.yml
Changed: Publishing the doc site is no longer automatically done by doc publishing branch. It's now done by a manual GitHub Actions workflow.
> Changed: Publishing the doc site is no longer automatically done by doc publishing branch

- src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala
- src/main/scala/devoops/data/GitHubReleaseKeys.scala
Close #195 - Add `devOops` prefix to avoid any potential naming conflicts with other plugins
> Close #195 - Add devOops prefix to avoid any potential naming conflicts with other plugins

- .github/workflows/build.yml
- .github/workflows/release.yml
- changelogs/2.0.0.md
- project/ProjectInfo.scala
* Support release to upload only artifacts (#125) ⚠️
* Replace `master` branch with `main` branch (#126)
* Create [document website](https://sbt-devoops.kevinly.dev) (#130)
* Replace `Just FP` with `Cats` (#138)
* **Drop sbt `0.13.x` support** (#141) ⚠️
* Adopt `Cats Effect` (#143)
* Use `http4s` instead of `github-api` (#146)
* GitHub release tasks should create a release without uploading artifacts (#163) ⚠️
* Change the default branch for `gitTagFrom` from `mater` to `main` (#167) ⚠️
* Add `SettingKey` for GitHub request timeout (#169)
* re-package from `kevinlee.sbt.devoops` to `devoops` (#173) ⚠️
* `scalacOptions` for Scala `2.13.3` and higher (#175)
* Remove `OldGitHubApi` (#177)
* Add a way to avoid the abuse rate limits in GitHub API (#179)
* Change `DevOopsGitReleasePlugin` to …
> sbt-devoops v2.0.0

- changelogs/2.1.0.md
- project/ProjectInfo.scala
* Remove invalid scalacOptions for Scala `2.11` (#208)
* Add Scala 3 `scalacOptions` (#210)
* Set no additional `scalacOptions` for unknown `scalaVersion` (#212)
* Add `noPublish` and `noDoc` settings to `DevOopsScalaPlugin` (#214)
> sbt-devoops v2.1.0

- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Close #101 - Use `sbt-devoops` itself to release
> Close #101 - Use sbt-devoops itself to release

- project/BuildTools.scala
- src/main/scala/devoops/DevOopsSbtExtraPlugin.scala
Close #222 - Add a way to detect the root project (i.e. `isRootProject`)
> Close #222 - Add a way to detect the root project (i.e. isRootProject)

- src/main/scala/devoops/DevOopsSbtExtraPlugin.scala
`DevOopsSbtExtraPlugin` is no longer dependent on Cats.
> DevOopsSbtExtraPlugin is no longer dependent on Cats

- changelogs/2.2.0.md
- project/ProjectInfo.scala
* Add a way to detect the root project (#222)
* Move `noPublish` and `noDoc` to `DevOopsSbtExtraPlugin` (#224)
* Use `sbt-devoops` itself to release (#101)
> sbt-devoops v2.2.0

- changelogs/2.3.0.md
* Add compiler plugins (#229)
* Publish directly to Maven Central (#231)
> sbt-devoops v2.3.0

- src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #235 - Make `strictEquality` non-default option in Scala 3
> Close #235 - Make strictEquality non-default option in Scala 3

- src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #241 - Add `scalacOptions` for Scala 2.13.6 and upgrade `compilerPlugin`s
> Close #241 - Add scalacOptions for Scala 2.13.6 and upgrade compilerPlugins

- changelogs/2.4.0.md
* Make `strictEquality` non-default option in Scala 3 (#235)
* Set `useAggressiveScalacOptions` to `true` to enable `strictEquality` in Scala 3.
* Add jar from sub-projects to `devOopsPackagedArtifacts` in `DevOopsGitHubReleasePlugin` (#236)
* `s"target/scala-*/${devOopsArtifactNamePrefix.value}*.jar"`
* `s"*/target/scala-*/${devOopsArtifactNamePrefix.value}*.jar"`
* `s"*/*/target/scala-*/${devOopsArtifactNamePrefix.value}*.jar"`
* Add more `-language` `scalacOptions` for Scala 2 (#240)
* `"-language:existentials"         // Existential types (besides wildcard types) can be written and inferred`
* `"-language:experimental.macros"  // Allow macro definition (besides implementation and application)`
* `"-language:implicitConversions"  // Allow definition of implicit functions called views` …
> sbt-devoops v2.4.0

- src/main/scala/devoops/DevOopsScalaPlugin.scala
Fix #245 - `strictEquality` should not be default in `scalacOptions` in Scala 3
> Fix #245 - strictEquality should not be default in scalacOptions in Scala 3

- changelogs/2.4.1.md
* `strictEquality` should not be default in `scalacOptions` in Scala 3 (#245)
> sbt-devoops v2.4.1

- src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #250 - Remove `-Ywarn-unused` from Scala 2.11
> Close #250 - Remove -Ywarn-unused from Scala 2.11

- changelogs/2.5.0.md
* Remove `-Ywarn-unused` from Scala `2.11` (#250)
* Add compiler plugins for Scala `2.12.14` (#252)
* Add macro `paradise` plugin for more of older Scala versions (#254)
> sbt-devoops v2.5.0

- build.sbt
Close #262 - Make `sbt-devoops` to add all `sbt-devoops` plugins
> Close #262 - Make sbt-devoops to add all sbt-devoops plugins

- changelogs/2.6.0.md
* Split `sbt-devoops` into multiple sub-projects (#258)
* Make `sbt-devoops` to add all `sbt-devoops-*` plugins (#262)
* `sbt-devoops-common`
* `sbt-devoops-scala`
* `sbt-devoops-sbt-extra`
* `sbt-devoops-github`
* `sbt-devoops-java`
> sbt-devoops v2.6.0

- sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #271 - Add `-source:future` to `scalacOptions` for Scala 3
> Close #271 - Add -source:future to scalacOptions for Scala 3

- changelogs/2.7.0.md
* Add `-source:future` to `scalacOptions` for Scala 3 (#271)
> sbt-devoops v2.7.0

- changelogs/2.8.0.md
* `DevOopsScalaPlugin` should support Scala `2.12.15` (#275)
> sbt-devoops v2.8.0

- changelogs/2.9.0.md
* Make `-source:future` for Scala 3 optional (#278)
> sbt-devoops v2.9.0

- changelogs/2.10.0.md
* Add a task to figure out GitHub org (username) and repo name (#283) - In `sbt-devoops-github`, `gitHubFindRepoOrgAndName` task
* Add a method to figure out GitHub org (username) and repo name #286 - In `sbt-devoops-github`, `findRepoOrgAndName` and `findRepoOrgAndNameWithLog(DevOopsLogLevel)` methods
> sbt-devoops v2.10.0

- changelogs/2.11.0.md
* Upgrade `just-sysprocess` to `1.0.0` (#293)
> sbt-devoops v2.11.0

- changelogs/2.14.0.md
* Support `kind-projector` for Scala `2.13.7` (#302)
> sbt-devoops v2.14.0

- changelogs/2.15.0.md
* Publish to `s01.oss.sonatype.org` (the new Maven central) (#308)
* Support `kind-projector` for Scala 2.13.8 (#318)
> sbt-devoops v2.15.0

- sbt-devoops-github/src/main/scala/devoops/data/SbtTaskError.scala
- sbt-devoops-github/src/main/scala/kevinlee/github/data/GitHubError.scala
- sbt-devoops-github/src/main/scala/kevinlee/http/HttpResponse.scala
- sbt-devoops-github/src/test/scala/kevinlee/http/HttpResponseSpec.scala
Close #328 - Add `errors` to `FailedResponseBodyJson`
> Close #328 - Add `errors` to `FailedResponseBodyJson`

- changelogs/2.16.0.md
* Add `errors` to `FailedResponseBodyJson` (#328)
> sbt-devoops v2.16.0

- build.sbt
- modules/sbt-devoops-common/src/main/scala/kevinlee/sbt/SbtCommon.scala
- modules/sbt-devoops-release-version-policy/src/main/scala/devoops/DevOopsReleaseVersionPolicy.scala
Close #348 - Add a plugin to support `sbt-release` with `sbt-version-policy`
> Close #348 - Add a plugin to support sbt-release with sbt-version-policy

- build.sbt
Issue #340 - Upgrade `effectie` and `logger-f` to `2.0.0-beta1`
> Issue #340 - Upgrade effectie and logger-f to 2.0.0-beta1

- changelogs/2.17.0.md
* Update `devOopsPackagedArtifacts` to include sub-projects with Scala.js (#351)
* Add a plugin to support `sbt-release` with `sbt-version-policy` (#348)
* Add `sbt-test` (`scripted`) to `sbt-devoops-scala` (#344)
* Upgrade `just-semver`, `cats` and `cats-effect` (#342)
* Upgrade libraries - `effectie`, `logger-f`, `http4s`, `circe`, `refined`, `hedgehog` and `extras` (#340)
* Move all sub-projects to modules (#338)
> sbt-devoops v2.17.0

- modules/sbt-devoops-release-version-policy/src/main/scala/devoops/DevOopsReleaseVersionPolicyPlugin.scala
Close #354 - Rename `DevOopsReleaseVersionPolicy` to `DevOopsReleaseVersionPolicyPlugin`
> Close #354 - Rename `DevOopsReleaseVersionPolicy` to `DevOopsReleaseVersionPolicyPlugin`

- changelogs/2.18.0.md
* Rename `DevOopsReleaseVersionPolicy` to `DevOopsReleaseVersionPolicyPlugin` (#354)
* Change `DevOopsReleaseVersionPolicyPlugin.trigger` to `allRequirements` (#356)
> sbt-devoops v2.18.0

- build.sbt
- modules/sbt-devoops-release-version-policy/src/main/scala/devoops/DevOopsReleaseVersionPolicyPlugin.scala
Close #359 - Set all `task`s and `setting`s in `DevOopsReleaseVersionPolicyPlugin` properly
* Move all `setting`s and `task`s in `ThisBuild` to `buildSettings`
* Make sure there is the right instruction to set up `versionPolicyIntention` and it's displayed when `versionPolicyIntention` is not set.
> Close #359 - Set all tasks and settings in DevOopsReleaseVersionPolicyPlugin properly

- changelogs/2.20.0.md
* [sbt-devoops-release-version-policy] Add better instruction for missing compatibility file (#364)
> sbt-devoops v2.20.0

- build.sbt
- modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala
Close #368 - Add `DevOopsStarterPlugin` plugin
- `DevOopsStarterPlugin` includes `sbt-scalafmt`, `sbt-scalafix` and `sbt-welcome` plugins
> Close #368 - Add `DevOopsStarterPlugin` plugin

- .github/workflows/doc-site-build-only.yml
Update: Fix `doc-site-build-only.yml` - not to publish auto build
> Update: Fix doc-site-build-only.yml - not to publish auto build

- changelogs/2.21.0.md
* Add `DevOopsStarterPlugin` plugin (#368)
* Move common http and GitHub related code to another core project (#370)
* Add task to write a default `.scalafmt.conf` file (#372)
* Add task to write default `.scalafix.conf` files (#375)
* Replace `http4s-blaze-client` with `http4s-ember-client` (#382)
> sbt-devoops v2.21.0

- changelogs/2.22.0.md
* [`sbt-devoops-starter`] paint logo with rainbow 🌈 colors in June (Pride Month) (#386)
> sbt-devoops v2.22.0

- changelogs/2.23.0.md
* [`sbt-devoops-scala`]: `DevOopsScalaPlugin` - Add support for new Scala versions and bump libraries (#390)
> sbt-devoops v2.23.0

- changelogs/2.24.0.md
* Upgrade `effectie` and `logger-f` to `2.0.0-beta4` (#401) - and update the code accordingly / also upgrade other libraries
* effectie `2.0.0-beta2` => `2.0.0-beta4`
* logger-f `2.0.0-beta2` => `2.0.0-beta4`
* sbt `1.8.0-RC1` => `1.8.0`
* hedgehog `0.9.0` => `0.10.1`
* cats `2.8.0` => `2.9.0`
* cats-effect `3.3.14` => `3.4.3`
* extras `0.20.0` => `0.26.0`
* just-semver `0.5.0` => `0.6.0`
* sbt-scalafmt `2.4.6` => `2.5.0`
* sbt-scalafix `0.10.3` => `0.10.4`
> sbt-devoops v2.24.0

- build.sbt
- modules/sbt-devoops-release-version-policy/src/main/scala/devoops/DevOopsReleaseVersionPolicyPlugin.scala
Fix #414 - `sbt-devoops-release-version-policy` cannot handle aggregate projects with different cross Scala versions
`sbt-release`, which is used by `sbt-devoops-release-version-policy`, can't handle aggregate projects with different cross Scala versions. ([Issue reproted](https://github.com/sbt/sbt-release/issues/214))
e.g.) So `sbt-release` can't handle a project structured like the following.
- root
- module1 - Scala 2 and 3
- module2 - Scala 2
It releases artifacts for only Scala 2.
This PR is a workaround to handle it based on https://github.com/sbt/sbt-release/issues/214#issuecomment-368407088 with a way to skip test if it's set to be skipped.
There are 
* an option to do or don't do cross Scala version release (default: do cross Scala versions) and
* an option to set a publish …
> Fix #414 - `sbt-devoops-release-version-policy` cannot handle aggregate projects with different cross Scala versions

- changelogs/2.24.1.md
* Fix: `sbt-devoops-release-version-policy` cannot handle aggregate projects with different cross Scala versions (`#414`)
`sbt-release`, which is used by `sbt-devoops-release-version-policy`, can't handle aggregate projects with different cross Scala versions. ([Issue reproted](https://github.com/sbt/sbt-release/issues/214))
e.g.) So `sbt-release` can't handle a project structured like the following.
* root
* module1 - Scala 2 and 3
* module2 - Scala 2
It releases artifacts for only Scala 2.
This Release fixed it to handle it properly based on https://github.com/sbt/sbt-release/issues/214#issuecomment-368407088 with a way to skip test if it's set to be skipped.
There are
* an option to do or don't do cross Scala version release (default: do cross Scala versions) and
* an option to set a …
> sbt-devoops v2.24.1

- build.sbt
- modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/build.sbt
- modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/project/build.properties
- modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/project/build.properties
- modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafix-conf-cross-scala-test-existing/build.sbt
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafix-conf-cross-scala-test-existing/project/build.properties
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafix-conf-cross-scala-test-new/build.sbt
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafix-conf-cross-scala-test-new/project/build.properties
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafix-conf-scala2-test-existing/project/build.properties
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafix-conf-scala2-test-new/project/build.properties
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafix-conf-scala3-test-existing/project/build.properties
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafix-conf-scala3-test-new/project/build.properties
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-existing/build.sbt
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-existing/project/build.properties
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-new/build.sbt
- modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-new/project/build.properties
- project/build.properties
- project/plugins.sbt
Close #418 - Upgrade Scala, sbt, sbt plugins and libraries
* Scala to 2.12.18
* sbt to 1.9.7
* sbt-scalafmt to 2.5.2
* sbt-scalafix to 0.11.1
* sbt-ci-release to 1.5.12
* sbt-wartremover to 3.1.3
* sbt-scoverage to 2.0.9
* sbt-coveralls to 1.3.11
* sbt-explicit-dependencies to 0.3.1
* sbt-welcome to 0.4.0
* sbt-devoops to 2.24.1
> Close #418 - Upgrade Scala, sbt, sbt plugins and libraries

- build.sbt
- modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpClient.scala
- modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpRequest.scala
- modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala
Close #421 - Upgrade libraries
* cats to 2.10.0
* cats-effect to 3.5.2
* extras to 0.44.0
* effectie to 2.0.0-beta13
* logger-f to 2.0.0-beta22
* refined to 0.11.0
* circe to 0.14.6
* http4s to 0.23.24
* just-semver to 0.13.0
> Close #421 - Upgrade libraries

- changelogs/3.0.0.md
* [`sbt-devoops-scala`] Remove `scalacOptions` in favor of `sbt-tpolecat` (#424)
* Now, `sbt-devoops-scala` requires `sbt-tpolecat`, so having `sbt-devoops-scala` also means having `sbt-tpolecat`.
* Upgrade Scala, sbt, sbt plugins and libraries (#418)
* Scala to `2.12.18`
* sbt to `1.9.7`
* sbt-scalafmt to `2.5.2`
* sbt-scalafix to `0.11.1`
* sbt-ci-release to `1.5.12`
* sbt-wartremover to `3.1.3`
* sbt-scoverage to `2.0.9`
* sbt-coveralls to `1.3.11`
* sbt-explicit-dependencies to `0.3.1`
* sbt-welcome to `0.4.0`
* sbt-devoops to `2.24.1`
* Upgrade libraries (#421)
* cats to `2.10.0`
* cats-effect to `3.5.2`
* extras to `0.44.0`
* effectie to `2.0.0-beta13`
* logger-f to `2.0.0-beta22`
* refined to `0.11.0`
* circe to `0.14.6`
* http4s to `0.23.24`
* just-semver to `0.13.0`
> sbt-devoops v3.0.0

- build.sbt
Close #439 - Bump libraries
* `cats-effect` to `3.5.3`
* `effectie` to `2.0.0-beta14`
* `logger-f` to `2.0.0-beta24`
* `refined` to `0.11.1`
* `http4s` to `0.23.25`
> Close #439 - Bump libraries

- changelogs/3.1.0.md
* [`sbt-devoops-scala`] Add `-Ymacro-annotations` to `scalacOptions` for Scala `2.13.3` and higher (#441)
* [`sbt-devoops-scala`] Update `kind-projector` version for new Scala `2.13`, `2.12` and `2.11` (#437)
* Bump libraries (#439)
* `cats-effect` to `3.5.3`
* `effectie` to `2.0.0-beta14`
* `logger-f` to `2.0.0-beta24`
* `refined` to `0.11.1`
* `http4s` to `0.23.25`
> sbt-devoops v3.1.0

- build.sbt
- modules/sbt-devoops-common/src/main/scala/kevinlee/sbt/io/Io.scala
- modules/sbt-devoops-release-version-policy/src/main/scala/devoops/DevOopsReleaseVersionPolicyPlugin.scala
- project/plugins.sbt
Update dependencies and plugins
- Updated `kind-projector` compiler plugin from 0.13.2 to 0.13.3
- Updated `hedgehog` from 0.10.1 to 0.12.0
- Updated `cats` from 2.10.0 to 2.13.0
- Updated `cats-effect` from 3.5.3 to 3.5.7
- Updated `effectie` from 2.0.0-beta14 to 2.0.0
- Updated `logger-f` from 2.0.0-beta24 to 2.1.18
- Updated `refined` from 0.11.1 to 0.11.3
- Updated `circe` from 0.14.6 to 0.14.12
- Added `circe-refined` version 0.15.1
- Updated `http4s` from 0.23.25 to 0.23.30
- Updated `just-semver` from 0.13.0 to 1.1.1
- Updated `commons-io` from 2.11.0 to 2.18.0
- Updated `sbt-tpolecat` from 0.5.0 to 0.5.2
- Updated `sbt-version-policy` from 3.2.1 to 3.2.1
- Updated `sbt-release` from 1.1.0 to 1.4.0
- Updated `sbt-scalafmt` from 2.5.2 to 2.5.4
- Updated `sbt-scalafix` from 0.11.1 to …
> Update dependencies and plugins

- changelogs/3.2.0.md
* Bump `sbt-version-policy` to 3.2.1 (#454)
* Bump libraries (#464)
- Updated `kind-projector` compiler plugin from 0.13.2 to 0.13.3
- Updated `hedgehog` from 0.10.1 to 0.12.0
- Updated `cats` from 2.10.0 to 2.13.0
- Updated `cats-effect` from 3.5.3 to 3.5.7
- Updated `effectie` from 2.0.0-beta14 to 2.0.0
- Updated `logger-f` from 2.0.0-beta24 to 2.1.18
- Updated `refined` from 0.11.1 to 0.11.3
- Updated `circe` from 0.14.6 to 0.14.12
- Added `circe-refined` version 0.15.1
- Updated `http4s` from 0.23.25 to 0.23.30
- Updated `just-semver` from 0.13.0 to 1.1.1
- Updated `commons-io` from 2.11.0 to 2.18.0
- Updated `sbt-tpolecat` from 0.5.0 to 0.5.2
- Updated `sbt-version-policy` from 3.2.1 to 3.2.1
- Updated `sbt-release` from 1.1.0 to 1.4.0
- Updated `sbt-scalafmt` from 2.5.2 to 2.5.4
- …
> sbt-devoops v3.2.0

- project/plugins.sbt
- website/docs/getting-started.md
- website/docs/gh-release-plugin/examples.md
- website/docusaurus.config.ts
- website/src/pages/versions.js
- Updated `sbt-docusaur` from 0.16.0 to 0.17.0
- Updated `sbt-devoops` version from 3.1.0 to 3.2.0 in `plugins.sbt`
- Updated `current` version label from 3.1.0 to 3.2.0 in `docusaurus.config.ts`
- Added version 3.1.0 to past versions in `versions.js`
> Update docs, and sbt-docusaur and sbt-devoops versions

- modules/sbt-devoops-common/src/main/scala/devoops/data/CommonKeys.scala
Fix #467 - Setting up `devOopsLogLevel` fails as it is imported twice
> Fix #467 - Setting up `devOopsLogLevel` fails as it is imported twice

- changelogs/3.2.1.md
* Setting up devOopsLogLevel fails as it is imported twice (#467)
* `s01.oss.sonatype.org` will be sunset on the 30th of June, 2025 (#469)
So it will no longer be possible to publish the artifacts to s01.oss.sonatype.org.
https://central.sonatype.org/news/20250326_ossrh_sunset/
> Announcement of the End-of-Life Sunset Date for OSSRH[⚓︎](https://central.sonatype.org/news/20250326_ossrh_sunset/#announcement-of-the-end-of-life-sunset-date-for-ossrh)
> The [OSSRH service](https://central.sonatype.org/publish/publish-guide/) will reach end-of-life on June 30th, 2025. This coincides with the [end-of-life date of the underlying technology, Sonatype's Nexus Repository Manager v2](https://help.sonatype.com/en/sonatype-nexus-repository-2-sunsetting-information.html).
So the new release should be …
> sbt-devoops v3.2.1
