kevin-lee/sbt-devoops

build.sbt, project/Dependencies.scala, project/ProjectInfo.scala
- Added: Hedgehog for testing
- Updated: Scala version and SBT version
=> Updated: project config

src/main/scala/io/kevinlee/sbt/SbtCommon.scala, src/test/scala/io/kevinlee/sbt/SbtCommonSpec.scala
Close #2 - There should be a way to have different elements for different versions
- Added: crossVersionProps to have different props for different versions
=> crossVersionProps to have different props for different versions

src/main/scala/io/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala, src/main/scala/io/kevinlee/semver/versions.scala
Close #1 - Add plugin to have default settings for Scala projects
=> SBT plugin for Scala projects

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
Close #11 - Add issue and pull request templates
=> Issue and pull request templates

.build-scripts/build-packages.sh, .build-scripts/build-project.sh, .build-scripts/env-info.sh, build.sbt, project/BuildTools.scala, project/plugins.sbt, src/main/scala/io/kevinlee/Common.scala, src/main/scala/io/kevinlee/CommonPredef.scala, src/main/scala/io/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala
Summary
=======
Close #12 - Add build scripts
***
Added:
-------
* build scripts for Semaphore CI and Coveralls
* SBT script to write the project version
=> Task #12 - Add build scripts

build.sbt, project/Deps.scala
Change object containing dependency libs info
=> Change object containing dependency libs info

.build-scripts/release-files-copy.sh, .build-scripts/semaphore-deploy.sh, build.sbt, project/Deps.scala, project/plugins.sbt
Preparation for publishing to bintray
=======
Close #18 - Publish to Bintray
=> Preparation for publishing to bintray

.build-scripts/build-packages.sh, .build-scripts/build-project.sh, .build-scripts/env-info.sh, .build-scripts/release-files-copy.sh, .build-scripts/semaphore-deploy.sh, ISSUE_TEMPLATE.md, LICENSE, PULL_REQUEST_TEMPLATE.md, README.md, build.sbt, changelogs/0.1.0.md, project/BuildTools.scala, project/Dependencies.scala, project/Deps.scala, project/ProjectInfo.scala, project/build.properties, project/plugins.sbt, project/scripted.sbt, src/main/scala/io/kevinlee/Common.scala, src/main/scala/io/kevinlee/CommonPredef.scala, src/main/scala/io/kevinlee/sbt/SbtCommon.scala, src/main/scala/io/kevinlee/sbt/devoops/DevOopsJavaPlugin.scala, src/main/scala/io/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala, src/main/scala/io/kevinlee/semver/versions.scala, src/test/scala/io/kevinlee/sbt/SbtCommonSpec.scala, src/test/scala/io/kevinlee/semver/Gens.scala, src/test/scala/io/kevinlee/semver/versionsSpec.scala
SBT DevOops v0.1.0
==================
[Changelog](https://github.com/Kevin-Lee/sbt-devoops/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A%220.1.0%22+)
Done
----
* Add plugin to have default settings for Scala projects (#1)
* There should be a way to have different elements for different versions (#2)
* Add data type to handle semantic version (#6)
* Add issue and pull request templates (#11)
* Add build scripts (#12)
* Plugin to support Java projects (#15)
* Publish to Bintray (#18)
=> SBT DevOops v0.1.0

.build-scripts/build-packages.sh, .build-scripts/build-project.sh, .build-scripts/env-info.sh, .build-scripts/release-files-copy.sh, .build-scripts/semaphore-deploy.sh, ISSUE_TEMPLATE.md, LICENSE, PULL_REQUEST_TEMPLATE.md, README.md, build.sbt, changelogs/0.1.0.md, project/BuildTools.scala, project/Deps.scala, project/ProjectInfo.scala, project/build.properties, project/plugins.sbt, project/scripted.sbt, src/main/scala/io/kevinlee/Common.scala, src/main/scala/io/kevinlee/CommonPredef.scala, src/main/scala/io/kevinlee/sbt/SbtCommon.scala, src/main/scala/io/kevinlee/sbt/devoops/DevOopsJavaPlugin.scala, src/main/scala/io/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala, src/main/scala/io/kevinlee/semver/versions.scala, src/test/scala/io/kevinlee/sbt/SbtCommonSpec.scala, src/test/scala/io/kevinlee/semver/Gens.scala, src/test/scala/io/kevinlee/semver/versionsSpec.scala
Release v0.1.0 => master
========================
Details: [v0.1.0](https://github.com/Kevin-Lee/sbt-devoops/releases/tag/v0.1.0)
=> Release v0.1.0 => master

project/ProjectInfo.scala
- Version: 0.1.0 => 0.2.0-SNAPSHOT
=> Version: 0.1.0 => 0.2.0-SNAPSHOT

build.sbt, project/BuildTools.scala, project/Deps.scala, project/ProjectInfo.scala, src/main/scala/io/kevinlee/git/Git.scala, src/main/scala/io/kevinlee/git/GitCommandError.scala, src/main/scala/io/kevinlee/git/GitCommandResult.scala, src/main/scala/io/kevinlee/git/sysProcess.scala, src/main/scala/io/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/io/kevinlee/sbt/devoops/data/SbtTaskError.scala, src/main/scala/io/kevinlee/sbt/devoops/data/SbtTaskResult.scala, src/main/scala/io/kevinlee/sbt/devoops/errors/SbtTaskError.scala
Summary
=======
Task #23 - Tag when merge into release branch happens (work in progress)
Details
=======
- SBT plugin to handle git checkout and tag
- types and methods to run git commands
- It can check if the current branch is the release branch
- Fix the bug in tag name
- Added: Other data and error for checking the current branch
- Added: sbt task result type
- It still probably need to fetch and merge the branch (git pull)
=> Git Tag in progress

src/main/scala/io/kevinlee/git/Git.scala, src/main/scala/io/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/io/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/io/kevinlee/sbt/devoops/data/SbtTaskError.scala
=> Refactored

src/main/scala/io/kevinlee/git/Git.scala, src/main/scala/io/kevinlee/git/GitCommandError.scala, src/main/scala/io/kevinlee/git/GitCommandResult.scala, src/main/scala/io/kevinlee/git/sysProcess.scala, src/main/scala/io/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Summary
=======
Close #32 - Push tag for release
Details
-------
* gitTag pushes tag to origin (or the repo specified) after tagging
=> Push tag for release

build.sbt, src/main/scala/kevinlee/Common.scala, src/main/scala/kevinlee/CommonPredef.scala, src/main/scala/kevinlee/git/Git.scala, src/main/scala/kevinlee/git/GitCommandError.scala, src/main/scala/kevinlee/git/GitCommandResult.scala, src/main/scala/kevinlee/git/sysProcess.scala, src/main/scala/kevinlee/sbt/SbtCommon.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsJavaPlugin.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskError.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskResult.scala, src/main/scala/kevinlee/semver/versions.scala, src/test/scala/kevinlee/sbt/SbtCommonSpec.scala, src/test/scala/kevinlee/semver/Gens.scala, src/test/scala/kevinlee/semver/versionsSpec.scala
Summary
=======
The package name `io.kevinlee` has renamed to just `kevinlee`.
The name of organization has changed from `io.kevinlee` to `kevinlee` as well.
=> Renamed: package io.kevinlee => kevinlee

project/Deps.scala, src/main/scala/kevinlee/sbt/io/Io.scala, src/main/scala/kevinlee/sbt/io/files.scala, src/test/scala/kevinlee/GenPlus.scala, src/test/scala/kevinlee/IoUtil.scala, src/test/scala/kevinlee/sbt/io/Gens.scala, src/test/scala/kevinlee/sbt/io/IoSpec.scala, src/test/scala/kevinlee/semver/Gens.scala, src/test/scala/kevinlee/test/IoUtil.scala, src/test/scala/kevinlee/test/data/io.scala
Summary
=======
Task #24 - Copy and rename packaged files
* A few methods in `Io` to copy files to the target location for GitHub release
=> Way to copy files for GitHub release

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Summary
=======
Task #24 - Copy and rename packaged files
* Added: DevOopsGitReleasePlugin has copyPackages to copy all `target/scala-*/$${name.value}*.jar` to `PROJECT_HOME/cd`
=> DevOopsGitReleasePlugin has copyPackages to copy the packaged files

.build-scripts/build-packages.sh, .build-scripts/build-project.sh, .build-scripts/release-files-copy.sh, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskError.scala, src/main/scala/kevinlee/sbt/io/Io.scala, src/test/scala/kevinlee/sbt/io/IoSpec.scala
Summary
=======
Close #24  - Copy ~~and rename~~ packaged files
=> Copy packaged files - fail when no package found

src/test/scala/kevinlee/sbt/io/Gens.scala
As [suggested by Charles](https://github.com/Kevin-Lee/sbt-devoops/pull/36#discussion_r261886442)
=> Better way to generate filenames in test

build.sbt, project/Deps.scala, src/main/scala/kevinlee/git/Git.scala, src/main/scala/kevinlee/git/GitCommandError.scala, src/main/scala/kevinlee/git/GitCommandResult.scala, src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/data/GitHubError.scala, src/main/scala/kevinlee/github/data/github.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskError.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskResult.scala, src/main/scala/kevinlee/sbt/io/Io.scala
Summary
=======
Close #22 - Support GitHub Release
* Added: GitHub Release
* copy packaged files to the ci folder
* git tag with the version (e.g. v0.1.0)
* GitHub release including uploading the package files and changelog
```sbt
sbt:test-project> gitHubRelease
>> copyPackages - Files copied from:
- /path/to/test-project/target/scala-2.11/test-project_2.11-0.1.0-SNAPSHOT-sources.jar
- /path/to/test-project/target/scala-2.11/test-project_2.11-0.1.0-SNAPSHOT.jar
- /path/to/test-project/target/scala-2.11/test-project_2.11-0.1.0-SNAPSHOT-javadoc.jar
- /path/to/test-project/target/scala-2.12/test-project_2.12-0.1.0-SNAPSHOT.jar
- /path/to/test-project/target/scala-2.12/test-project_2.12-0.1.0-SNAPSHOT-sources.jar
- /path/to/test-project/target/scala-2.12/test-project_2.12-0.1.0-SNAPSHOT-javado …
```
=> Close #22 - Support GitHub Release

src/test/scala/kevinlee/sbt/io/Gens.scala, src/test/scala/kevinlee/sbt/io/IoSpec.scala
* Fixed: bug in Gen for filenames to test the copy method
=> Fixed bug in Gen for filenames to test the copy method

src/main/scala/kevinlee/sbt/SbtCommon.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskError.scala, src/main/scala/kevinlee/sbt/io/Io.scala
* Changed: sys.error => throw new MessageOnlyException
=> sys.error => throw new MessageOnlyException

README.md
* Added: README.md - how to get and use
=> Added: README.md - how to get and use

changelogs/0.2.0.md, src/main/scala/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala
* Added: Changelog for 0.2.0
* Changed: indentation fix
=> Changelog for 0.2.0

.build-scripts/build-packages.sh, .build-scripts/build-project-simple.sh, .build-scripts/release-files-copy.sh, project/ProjectInfo.scala
Summary
=======
Changed: build scripts
* Changed: build scripts
* Changed: Scala version: 2.12.7 => 2.12.8 / sbt version: 1.2.6 => 1.2.8
=> Changed: build scripts

build.sbt, project/Deps.scala, src/main/scala/kevinlee/git/Git.scala, src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/GitHubTask.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/kevinlee/semver/versions.scala, src/test/scala/kevinlee/semver/versionsSpec.scala
=> Changed: clean up

src/main/scala/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala
Summary
=======
Close #60 - Add default scalac options to DevOopsScalaPlugin for Scala 2.13
=> Close #60 - Add default scalac options to DevOopsScalaPlugin for Scala 2.13

README.md, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Summary
=======
Close #56 - Setting to select packaged artifacts
=> Close #56 - Setting to select packaged artifacts

README.md, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskError.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskResult.scala
Summary
=======
Close #53 - SNAPSHOT version should not be released
=> Close #53 - SNAPSHOT version should not be released

README.md, build.sbt, project/ProjectInfo.scala
Summary
=======
* Changed: `build.sbt` - Scala 2.12.8 => 2.12.10 / sbt 1.2.6 => 1.2.8
* Removed: test coverage badge from `README.md`
=> Changed: config

src/main/scala-2.10/kevinlee/fp/compat/EitherCompat.scala, src/main/scala-2.12/kevinlee/fp/compat/EitherCompat.scala, src/main/scala/kevinlee/fp/Applicative.scala, src/main/scala/kevinlee/fp/EitherT.scala, src/main/scala/kevinlee/fp/Equal.scala, src/main/scala/kevinlee/fp/Functor.scala, src/main/scala/kevinlee/fp/Monad.scala, src/main/scala/kevinlee/fp/Monoid.scala, src/main/scala/kevinlee/fp/SemiGroup.scala, src/main/scala/kevinlee/fp/WriterT.scala, src/main/scala/kevinlee/fp/instances/ByteEqualInstance.scala
Summary
=======
Updated internal `just-fp` code. Mostly copied from https://github.com/Kevin-Lee/just-fp
=> Updated internal just-fp code

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Summary
=======
Close #75 - Take `gitTag` out of `gitHubRelease` and add one having both
=> Close #75 - Take gitTag out of gitHubRelease and add one having both

src/main/scala/kevinlee/fp/package.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskResult.scala
Summary
=======
Refactor to have proper task history
=> Refactor to have proper task history

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
Updated: issue and PR templates
=> Updated: issue and PR templates

src/main/scala/kevinlee/git/Git.scala, src/main/scala/kevinlee/git/GitCmd.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Close #82 - Fix bug in git tag fetching
=> Close #82 - Fix bug in git tag fetching

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskError.scala
Close #83 - Add actifacts requirement option
=> Close #83 - Add actifacts requirement option

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/kevinlee/sbt/io/Io.scala
=> Code formatting

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Close #87 - `gitTagAndGitHubRelease` tags when there is no artifact to upload
=> Close #87 - gitTagAndGitHubRelease tags when there is no artifact to upload

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Close #89 - Change `gitHubReleaseWithArtifacts` to `artifactsRequiredForGitHubRelease`
=> Close #89 - Change gitHubReleaseWithArtifacts to artifactsRequiredForGitHubRelease

README.md, changelogs/1.0.0.md, project/ProjectInfo.scala
=> Prepare to release v1.0.0

build.sbt
Close #92 - Changed: Group ID from `kevinlee` to `io.kevinlee` for publishing to some central repo
=> Close #92 - Changed: Group ID from kevinlee to io.kevinlee for publishing to some central repo

build.sbt, changelogs/1.0.1.md, project/ProjectInfo.scala
* Release to change Group ID from `kevinlee` to `io.kevinlee`
=> sbt DevOops v1.0.1

README.md
Updated: README.md - new version info
=> Updated: README.md - new version info

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh, build.sbt, project/Deps.scala
Close #94 - Use GitHub Actions
=> Close #94 - Use GitHub Actions

.github/workflows/release.yml, README.md, changelogs/1.0.2.md, project/ProjectInfo.scala
=> Prepare to release 1.0.2

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh, build.sbt, project/ProjectInfo.scala
Close #107 - Upgrade sbt from `1.2.8` to `1.3.3`
=> Close #107 - Upgrade sbt to 1.3.3

.github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh
=> Fixed: build scripts

build.sbt, project/plugins.sbt
Upgraded: `sbt-coveralls` `1.2.2` => `1.2.7`
=> Upgraded: sbt-coveralls 1.2.2 => 1.2.7

src/main/scala/kevinlee/sbt/devoops/DevOopsJavaPlugin.scala
Close #113 - Remove `javacOptions` causing problems.
=> Close #113 - Remove javacOptions causing problems

src/main/scala/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala
Close #117 - Add `partial-unification` to `scalacOptions`
=> Close #117 - Add partial-unification to scalacOptions

project/build.properties
Close #119 - Upgrade sbt to `1.3.4`
=> Close #119 - Upgrade sbt to 1.3.4

project/plugins.sbt, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Added: sbt plugin - `partial-unification`
Changed: a minor change
=> Added: sbt plugin - partial-unification

.github/workflows/build.yml, .github/workflows/sbt-build.sh
Updated: GitHub Actions build - use matrix
=> Updated: GitHub Actions build - use matrix

.github/workflows/release.yml
Updated: GitHub Actions release - use matrix
=> Updated: GitHub Actions release - use matrix

.github/workflows/publish-github-pages.yml, build.sbt, project/plugins.sbt, website/docs/gh-release-plugin/examples.md, website/src/pages/index.js
Close #130 - GitHub Actions to build and publish the doc website
=> Close #130 - GitHub Actions to build and publish the doc website

website/src/pages/index.js
=> Updated: the site metadata

project/build.properties
=> Upgraded: sbt 1.3.4 => 1.3.13

build.sbt, src/main/scala/kevinlee/git/Git.scala, src/main/scala/kevinlee/git/sysProcess.scala, src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/GitHubTask.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskResult.scala, src/main/scala/kevinlee/sbt/io/Io.scala, src/test/scala/kevinlee/Gens.scala
Close #138 - Replace Just FP with Cats
=> Close #138 - Replace Just FP with Cats

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt
Close #141 - Drop sbt `0.13.x` support
=> Close #141 - Drop sbt 0.13.x support

build.sbt, src/main/scala/kevinlee/git/Git.scala, src/main/scala/kevinlee/github/GitHubTask.scala, src/main/scala/kevinlee/github/OldGitHubApi.scala, src/main/scala/kevinlee/github/data/GitHubError.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskResult.scala
Close #143 - Adopt Cats Effect
=> Close #143 - Adopt Cats Effect

build.sbt
=> Add: github4s and newtype

build.sbt
Issue #146 - Remove github4s from build.sbt
=> Issue #146 - Remove github4s from build.sbt

src/main/scala/kevinlee/http/HttpClient.scala, src/main/scala/kevinlee/http/HttpError.scala, src/main/scala/kevinlee/http/HttpRequest.scala, src/main/scala/kevinlee/http/HttpResponse.scala
Issue #146 - Add `HttpClient` using http4s
=> Issue #146 - Add HttpClient using http4s

src/main/scala/kevinlee/github/data/GitHubRelease.scala, src/main/scala/kevinlee/github/data/User.scala
Issue #146 - New data types for GitHub release
=> Issue #146 - New data types for GitHub release

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/data/github.scala
Issue #146 - Add 'create GitHub release'
=> Issue #146 - Add 'create GitHub release'

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/http/HttpClient.scala, src/main/scala/kevinlee/http/HttpError.scala, src/main/scala/kevinlee/http/HttpRequest.scala
Issue #146 - Add 'find GitHub release'
=> Issue #146 - Add 'find GitHub release'

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/data/GitHubRelease.scala
Issue #146 - Add 'update GitHub release'
=> Issue #146 - Add 'update GitHub release'

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/http/HttpRequest.scala
Issue #146 - A simpler way to handle request body JSON
=> Issue #146 - A simpler way to handle request body JSON

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/data/GitHubRelease.scala, src/main/scala/kevinlee/http/HttpClient.scala, src/main/scala/kevinlee/http/HttpError.scala, src/main/scala/kevinlee/http/HttpRequest.scala
Issue #146 - Add upload assets to GitHub release
=> Issue #146 - Add upload assets to GitHub release

.scalafmt.conf, src/main/scala/kevinlee/github/data/GitHubError.scala
=> Formatting

src/main/scala/kevinlee/github/data/GitHubError.scala, src/main/scala/kevinlee/http/HttpClient.scala, src/main/scala/kevinlee/http/HttpError.scala, src/main/scala/kevinlee/http/HttpResponse.scala
Issue #146 - Added: authentication to GitHub API failure handling
=> Issue #146 - Added: authentication to GitHub API failure handling

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/data/GitHubError.scala, src/main/scala/kevinlee/github/data/GitHubRelease.scala, src/main/scala/kevinlee/http/HttpClient.scala, src/main/scala/kevinlee/http/HttpError.scala, src/main/scala/kevinlee/http/HttpRequest.scala
Issue #146 - Fixed: A bug in uploading a bigger file to GitHub release
Related to http4s/http4s#4303
=> Issue #146 - Fixed: A bug in uploading a bigger file to GitHub release

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/http/HttpClient.scala, src/main/scala/kevinlee/http/HttpRequest.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Close #146 - Use http4s instead of github4s
=> Close #146 - Use http4s instead of github4s

build.sbt
* Scala 2.12.10 => 2.12.12
* http4s 0.21.15 => 0.21.16
* logger-f-slf4j for testing
=> Upgraded: Scala and http4s

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/GitHubTask.scala, src/main/scala/kevinlee/github/data/GitHubError.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala
Close #125 - Support release to upload only artifacts
=> Close #125 - Support release to upload only artifacts

src/main/scala/kevinlee/http/HttpRequest.scala
* `Show[HttpRequest]` to properly protect some confidential info (e.g. password, access token, etc.)
* Use show in `HttpRequest.toString` to hide the confidential info
=> Protect sensitive info in http headers

src/main/scala/kevinlee/sbt/devoops/data/SbtTask.scala, src/main/scala/kevinlee/sbt/devoops/data/SbtTaskError.scala
Fixed: Failure details were not printed out
=> Fixed: Failure details were not printed out

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Close #163 - GitHub release tasks should create a release without uploading artifacts
=> Close #163 - GitHub release tasks should create a release without uploading artifacts

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Close #169 - Add `SettingKey` for GitHub request timeout
=> Close #169 - Add SettingKey for GitHub request timeout

src/main/scala/kevinlee/http/HttpError.scala, src/main/scala/kevinlee/http/HttpRequest.scala, src/main/scala/kevinlee/http/HttpResponse.scala, src/main/scala/kevinlee/ops/instances.scala, src/main/scala/kevinlee/ops/package.scala
Added and changed: reorganize utility functions and protect sensitive data in `HttpResponse`
=> Added and changed: reorganize utility functions and protect sensitive data in HttpResponse

src/main/scala/kevinlee/sbt/SbtCommon.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala, src/test/scala/kevinlee/sbt/SbtCommonSpec.scala
Close #175 - `scalacOptions` for Scala 2.13.3 and higher
=> Close #175 - scalacOptions for Scala 2.13.3 and higher

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Close #179 - Add a way to avoid the abuse rate limits in GitHub API
=> Close #179 - Add a way to avoid the abuse rate limits in GitHub API

src/main/scala/kevinlee/git/Git.scala, src/main/scala/kevinlee/github/data/GitHub.scala, src/test/scala/kevinlee/test/IoUtil.scala, src/test/scala/kevinlee/test/data.scala, src/test/scala/kevinlee/test/data/io.scala
Changed: `value classes` with `newtypes`
=> Changed: value classes with newtypes

src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/data/GitHub.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala
Changed: removed duplicate GitHub repo type and changed its name and field names
=> Changed: removed duplicate GitHub repo type and changed its name and field names

src/main/scala/kevinlee/github/GitHubApi.scala
=> Added: User-Agent header

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/data/GitHubReleaseKeys.scala, src/main/scala/kevinlee/sbt/devoops/data/GitHubReleaseOps.scala
Changed: `SettingKey`s and methods in `DevOopsGitReleasePlugin.autoImport` to `trait`s
=> Changed: SettingKeys and methods in DevOopsGitReleasePlugin.autoImport to traits

src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, src/main/scala/devoops/DevOopsJavaPlugin.scala, src/main/scala/devoops/DevOopsScalaPlugin.scala, src/main/scala/devoops/data/GitHubReleaseKeys.scala, src/main/scala/devoops/data/GitHubReleaseOps.scala, src/main/scala/devoops/data/SbtTask.scala, src/main/scala/devoops/data/SbtTaskError.scala, src/main/scala/devoops/data/SbtTaskResult.scala
Close #173 - re-package from `kevinlee.sbt.devoops` to `devoops`
=> Close #173 - re-package from kevinlee.sbt.devoops to devoops

src/main/scala/kevinlee/sbt/devoops/DevOopsGitReleasePlugin.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsJavaPlugin.scala, src/main/scala/kevinlee/sbt/devoops/DevOopsScalaPlugin.scala
Close #191 - Add `@deprecated` `Plugin`s as a guide to use the new ones.
=> Close #191 - Add @deprecated Plugins as a guide to use the new ones

src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, src/main/scala/devoops/data/DevOopsLogLevel.scala, src/main/scala/devoops/data/GitHubReleaseKeys.scala, src/main/scala/devoops/data/SbtTask.scala, src/main/scala/devoops/data/SbtTaskError.scala, src/main/scala/kevinlee/github/GitHubApi.scala, src/main/scala/kevinlee/github/data/GitHubError.scala, src/main/scala/kevinlee/http/HttpClient.scala, src/main/scala/kevinlee/http/HttpError.scala, src/main/scala/kevinlee/http/HttpRequest.scala, src/main/scala/kevinlee/http/HttpResponse.scala
Close #194 - Add log level for `sbt-devoops` tasks
=> Close #194 - Add log level for sbt-devoops tasks

project/plugins.sbt
Issue #199 - Upgraded: sbt-docusaur `0.1.2` => `0.3.0`
=> Issue #199 - Upgraded: sbt-docusaur 0.1.2 => 0.3.0

.github/workflows/build.yml, .github/workflows/manual-publish-github-pages.yml, .github/workflows/release.yml
Updated: GitHub Actions cache setup
=> Updated: GitHub Actions cache setup

website/docs/gh-release-plugin/config-and-run.md
Issue #199 - update docs for `v2.0.0`
=> Issue #199 - update docs for v2.0.0

website/docs/gh-release-plugin/config-and-run.md
Issue #199 - update docs for v2.0.0 and fix the broken link
=> Issue #199 - update docs for v2.0.0 and fix the broken link

website/docusaurus.config.js, website/src/pages/versions.js
Issue #199 - Fix versions page in the doc site
=> Issue #199 - Fix versions page in the doc site

src/main/scala/devoops/DevOopsScalaPlugin.scala
Fix #208 - Remove invalid `scalacOptions` for Scala `2.11`
=> Fix #208 - Remove invalid scalacOptions for Scala 2.11

src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #210 - Add Scala 3 `scalacOptions`
=> Close #210 - Add Scala 3 scalacOptions

src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #212 - Set no additional `scalacOptions` for unknown `scalaVersion`
=> Close #212 - Set no additional scalacOptions for unknown scalaVersion

src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #214 - Add `noPublish` and `noDoc` settings to `DevOopsScalaPlugin`
=> Close #214 - Add noPublish and noDoc settings to DevOopsScalaPlugin

.github/workflows/release.yml, .github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh, project/build.properties
Upgraded: sbt `1.3.13` => `1.4.9`
=> Upgraded: sbt 1.3.13 => 1.4.9

build.sbt, project/build.properties
Updated: sbt `1.4.9` => `1.5.0` / project config
=> Updated: sbt 1.4.9 => 1.5.0 / project config

src/main/scala/devoops/DevOopsSbtExtraPlugin.scala, src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #224 - Move `noPublish` and `noDoc` to `DevOopsSbtExtraPlugin`
=> Close #224 - Move noPublish and noDoc to DevOopsSbtExtraPlugin

.github/workflows/m-gh-release-only.yml
Updated: GitHub Actions config to fix missing GH access token for release and adding a way to do manual GH release
=> Updated: GitHub Actions config to fix missing GH access token for release and adding a way to do manual GH release

src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #229 - Add compiler plugins
=> Close #229 - Add compiler plugins

README.md, website/docs/getting-started.md, website/docs/gh-release-plugin/examples.md
=> Updated: docs

src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, src/main/scala/devoops/data/GitHubReleaseKeys.scala, src/test/scala/kevinlee/sbt/io/IoSpec.scala
Close #236 - Add `jar` from sub-projects to `devOopsPackagedArtifacts` in `DevOopsGitHubReleasePlugin`
=> Close #236 - Add jar from sub-projects to devOopsPackagedArtifacts in DevOopsGitHubReleasePlugin

src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #240 - Add more `-language` `scalacOptions` for Scala 2
=> Close #240 - Add more -language scalacOptions for Scala 2

website/docs/getting-started.md, website/docs/gh-release-plugin/examples.md
Updated: docs - with the new version info
=> Updated: docs - with the new version info

src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #252 - Add compiler plugins for Scala `2.12.14`
=> Close #252 - Add compiler plugins for Scala 2.12.14

src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #254 - Add macro paradise plugin for more of older Scala versions
=> Close #254 - Add macro paradise plugin for more of older Scala versions

project/plugins.sbt
- `sbt-devoops-scala`
- `sbt-devoops-sbt-extra`
- `sbt-devoops-github`
=> Upgraded: sbt-devoops 2.5.0 => 2.6.0

sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #275 - `DevOopsScalaPlugin` should support Scala `2.12.15`
=> Close #275 - DevOopsScalaPlugin should support Scala 2.12.15

sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #278 - Make `-source:future` for Scala 3 optional
=> Close #278 - Make -source:future for Scala 3 optional

.scalafmt.conf, build.sbt, sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubPlugin.scala, sbt-devoops-github/src/main/scala/kevinlee/github/data/GitHub.scala, sbt-devoops-github/src/test/scala/kevinlee/github/data/GitHubSpec.scala
Close #283 - Add a task to figure out GitHub username and repo name
=> Close #283 - Add a task to figure out GitHub org (username) and repo name

build.sbt, project/plugins.sbt
- sbt-docusaur `0.5.0` => `0.6.0`
- sbt-devoops `2.6.0` => `2.9.0`
=> Upgraded: sbt-plugins

sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubPlugin.scala, sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, sbt-devoops-github/src/main/scala/devoops/data/Logging.scala, sbt-devoops-github/src/main/scala/kevinlee/github/data/GitHub.scala
Close #286 - Add a method to figure out GitHub org (username) and repo name
=> Close #286 - Add a method to figure out GitHub org (username) and repo name

build.sbt
Upgraded: http4s `0.21.23` => `0.21.28`
=> Upgraded: http4s 0.21.23 => 0.21.28

build.sbt
=> Removed: unused config

.github/workflows/manual-publish-github-pages.yml, project/plugins.sbt
- `sbt-docusaur` `0.6.0` => `0.7.0`
- `sbt-devoops` `2.9.0` => `2.10.0`
=> Upgraded: sbt plugins

build.sbt, sbt-devoops-github/src/main/scala/kevinlee/github/data/GitHub.scala
Close #293 - Upgrade `just-sysprocess` to `1.0.0`
=> Close #293 - Upgrade just-sysprocess to 1.0.0

sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #302 - Support kind-projector for Scala `2.13.7`
=> Close #302 - Support kind-projector for Scala 2.13.7

project/build.properties
Upgrade: sbt `1.5.5` => `1.5.8`
=> Upgrade: sbt 1.5.5 => 1.5.8

.github/pr-labeler.yml, .github/workflows/pr-labeler.yml
Add: PR Labeler - GitHub Actions
=> Add: PR Labeler - GitHub Actions

.scalafmt.conf, sbt-devoops-common/src/main/scala/kevinlee/sbt/io/files.scala, sbt-devoops-common/src/test/scala/kevinlee/Gens.scala, sbt-devoops-common/src/test/scala/kevinlee/sbt/SbtCommonSpec.scala, sbt-devoops-common/src/test/scala/kevinlee/sbt/io/IoSpec.scala, sbt-devoops-common/src/test/scala/kevinlee/test/data.scala, sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, sbt-devoops-github/src/main/scala/devoops/data/DevOopsLogLevel.scala, sbt-devoops-github/src/main/scala/devoops/data/GitHubReleaseOps.scala, sbt-devoops-github/src/main/scala/devoops/data/Logging.scala, sbt-devoops-github/src/main/scala/devoops/data/SbtTaskError.scala, sbt-devoops-github/src/main/scala/kevinlee/git/Git.scala, sbt-devoops-github/src/main/scala/kevinlee/git/GitCmd.scala, sbt-devoops-github/src/main/scala/kevinlee/git/sysProcess.scala, sbt-devoops-github/src/main/scala/kevinlee/github/GitHubApi.scala, sbt-devoops-github/src/main/scala/kevinlee/github/GitHubTask.scala, sbt-devoops-github/src/main/scala/kevinlee/github/data/GitHub.scala, sbt-devoops-github/src/main/scala/kevinlee/github/data/GitHubError.scala, sbt-devoops-github/src/main/scala/kevinlee/github/data/GitHubRelease.scala, sbt-devoops-github/src/main/scala/kevinlee/http/HttpRequest.scala, sbt-devoops-github/src/main/scala/kevinlee/http/HttpResponse.scala, sbt-devoops-github/src/test/scala/kevinlee/github/data/GitHubSpec.scala, sbt-devoops-java/src/main/scala/devoops/DevOopsJavaPlugin.scala, sbt-devoops-sbt-extra/src/main/scala/devoops/DevOopsSbtExtraPlugin.scala, sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala
Update: `.scalafmt.conf` and reformat
=> Update: .scalafmt.conf and reformat

build.sbt, project/plugins.sbt
Close #308 - Publish to `s01.oss.sonatype.org` (the new Maven central)
=> Close #308 - Publish to s01.oss.sonatype.org (the new Maven central)

sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #318 - Support Scala `2.13.8`
=> Close #318 - Support Scala 2.13.8

project/build.properties
Upgrade: sbt `1.5.8` => `1.6.2`
=> Upgrade: sbt 1.5.8 => 1.6.2

website/package-lock.json, website/package.json
Downgrade Docusaurus `2.0.0-beta.17` => `2.0.0-beta.14` - temporary fix for broken DocSearch
=> Downgrade Docusaurus 2.0.0-beta.17 => 2.0.0-beta.14 - temporary fix for broken DocSearch

build.sbt, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubPlugin.scala, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, modules/sbt-devoops-github/src/main/scala/devoops/data/SbtTask.scala, modules/sbt-devoops-github/src/main/scala/kevinlee/git/Git.scala, modules/sbt-devoops-github/src/main/scala/kevinlee/github/GitHubApi.scala, modules/sbt-devoops-github/src/main/scala/kevinlee/github/data/GitHub.scala, modules/sbt-devoops-github/src/main/scala/kevinlee/http/HttpClient.scala, modules/sbt-devoops-github/src/main/scala/kevinlee/http/HttpRequest.scala, modules/sbt-devoops-github/src/main/scala/kevinlee/http/HttpResponse.scala, modules/sbt-devoops-github/src/test/scala/kevinlee/github/data/GitHubSpec.scala
Close #340 - Upgrade libraries - `effectie`, `logger-f`, `http4s`, `circe`, `refined`, `hedgehog` and `extras`
=> Close #340 - Upgrade libraries - `effectie`, `logger-f`, `http4s`, `circe`, `refined`, `hedgehog` and `extras`

build.sbt, modules/sbt-devoops-common/src/test/scala/kevinlee/Gens.scala
Close #342 - Upgrade `just-semver`, `cats` and `cats-effect`
=> Close #342 - Upgrade just-semver, cats and cats-effect

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/build.sbt, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/project/Dependencies.scala, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/project/build.properties, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/project/plugins.sbt, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/src/main/scala/example/Hello.scala, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/src/test/scala/example/HelloSpec.scala, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/test, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/build.sbt, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/project/Dependencies.scala, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/project/build.properties, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/project/plugins.sbt, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/src/main/scala/example/Hello.scala, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/src/test/scala/example/HelloSpec.scala, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/test
Close #344 - Add `sbt-test` (`scripted`) to `sbt-devoops-scala`
=> Close #344 - Add sbt-test (scripted) to sbt-devoops-scala

.scalafmt.conf
Update: .scalafmt.conf - `3.2.1` => `3.4.3` / more rule
=> Update: .scalafmt.conf - 3.2.1 => 3.4.3 / more rule

modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala
Close #351 - Update devOopsPackagedArtifacts to include sub-projects with Scala.js
=> Close #351 - Update devOopsPackagedArtifacts to include sub-projects with Scala.js

modules/sbt-devoops-release-version-policy/src/main/scala/devoops/DevOopsReleaseVersionPolicyPlugin.scala
Close #356 - Change `DevOopsReleaseVersionPolicyPlugin.trigger` to `allRequirements`
=> Close #356 - Change DevOopsReleaseVersionPolicyPlugin.trigger to allRequirements

build.sbt, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubPlugin.scala, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, modules/sbt-devoops-github/src/main/scala/kevinlee/github/GitHubApi.scala, modules/sbt-devoops-github/src/main/scala/kevinlee/http/HttpClient.scala, modules/sbt-devoops-github/src/main/scala/kevinlee/http/HttpRequest.scala, modules/sbt-devoops-github/src/test/scala/kevinlee/github/data/GitHubSpec.scala
Close #361 - Upgrade libraries
* cats-effect `2.5.4` => `3.3.5`
* refined `0.9.27` => `0.9.28`
* http4s `0.22.12` => `0.23.11`
* commons-io `2.8.0` => `2.11.0`
***
Add `extras-hedgehog-cats-effect3` `0.13.0` for testing
=> Close #361 - Upgrade libraries

modules/sbt-devoops-release-version-policy/src/main/scala/devoops/DevOopsReleaseVersionPolicyPlugin.scala
Close #364 - [sbt-devoops-release-version-policy] Add better instruction for missing compatibility file
=> Close #364 - [sbt-devoops-release-version-policy] Add better instruction for missing compatibility file

build.sbt, project/plugins.sbt
=> Add: sbt-welcome

modules/sbt-devoops-starter/src/main/resources/scalafmt/default-scalafmt.conf.template, modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala, modules/sbt-devoops-starter/src/main/scala/devoops/types/StarterError.scala, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-existing/.scalafmt.conf, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-existing/build.sbt, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-existing/original-scalafmt.conf, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-existing/project/build.properties, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-existing/project/plugins.sbt, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-existing/test, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-new/build.sbt, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-new/project/build.properties, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-new/project/plugins.sbt, modules/sbt-devoops-starter/src/sbt-test/sbt-devoops-starter/write-default-scalafmt-conf-test-new/test
Close #372 - Add task to write a default `.scalafmt.conf` file
=> Close #372 - Add task to write a default `.scalafmt.conf` file

modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/build.sbt, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/project/Dependencies.scala, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/build.sbt, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/project/Dependencies.scala
Small changes in `sbt-test` for `sbt-devoops-scala`
=> Small changes in sbt-test for sbt-devoops-scala

modules/sbt-devoops-starter/src/main/resources/scalafix/default-scalafix-scala2.conf.template, modules/sbt-devoops-starter/src/main/resources/scalafix/default-scalafix-scala3.conf.template, modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala
Close #375 - Add task to write default `.scalafix.conf` files
=> Close #375 - Add task to write default `.scalafix.conf` files

.github/workflows/manual-publish-github-pages.yml, website/package-lock.json, website/package.json
Upgrade: Node `14.16.0` => `16.15.0` and Docusaurus `2.0.0-beta.14` => `2.0.0-beta.21`
=> Upgrade: Node 14.16.0 => 16.15.0 and Docusaurus 2.0.0-beta.14 => 2.0.0-beta.21

.github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml
Update: Add auto doc site build
=> Update: Add auto doc site build

build.sbt, modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala
Update: `sbt-devoops-starter` - change alias color and add aliases for cross version commands
=> Update: sbt-devoops-starter - change alias color and add aliases for cross version commands

build.sbt, modules/sbt-devoops-common/src/main/scala/devoops/data/CommonKeys.scala, modules/sbt-devoops-common/src/main/scala/kevinlee/sbt/io/Io.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/GitHubApi.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/data/GitHub.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/data/GitHubRelease.scala, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpRequest.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpResponse.scala, modules/sbt-devoops-http-core/src/test/scala/kevinlee/http/HttpResponseSpec.scala, modules/sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala, modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala
Close #382 - Replace `http4s-blaze-client` with `http4s-ember-client`
=> Close #382 - Replace http4s-blaze-client with http4s-ember-client

build.sbt, project/plugins.sbt
=> Update: clean up dependencies

build.sbt, modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala
Close #386 - [`sbt-devoops-starter`] paint logo with rainbow 🌈 colors in June (Pride Month)
=> Close #386 - [sbt-devoops-starter] paint logo with rainbow 🌈 colors in June (Pride Month)

build.sbt, modules/sbt-devoops-common/src/test/scala/kevinlee/Gens.scala, modules/sbt-devoops-common/src/test/scala/kevinlee/test/IoUtil.scala, modules/sbt-devoops-common/src/test/scala/kevinlee/test/data.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/git/Git.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/data/GitHub.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/data/GitHubError.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/data/GitHubRelease.scala, modules/sbt-devoops-github-core/src/test/scala/kevinlee/github/data/GitHubSpec.scala, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubPlugin.scala, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpClient.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpRequest.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpResponse.scala, modules/sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala, modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala, project/build.properties, project/plugins.sbt
Close #390 - `DevOopsScalaPlugin` - Add support for new Scala versions and bump libraries
=> Close #390 - DevOopsScalaPlugin - Add support for new Scala versions and bump libraries

project/plugins.sbt
Upgrade: sbt-docusaur `0.11.0` => `0.12.0`
=> Upgrade: sbt-docusaur 0.11.0 => 0.12.0

project/build.properties, project/plugins.sbt
Bump sbt `1.7.1` => `1.8.0-RC1` / sbt-scoverage `1.5.1` => `2.0.6` / sbt-coveralls `1.2.7` => `1.3.2`
=> Bump sbt `1.7.1` => `1.8.0-RC1` / sbt-scoverage `1.5.1` => `2.0.6` / sbt-coveralls `1.2.7` => `1.3.2`

website/package-lock.json, website/package.json
Upgrade: Docusaurus 2.0.0-beta.21 => 2.2.0
=> Upgrade: Docusaurus 2.0.0-beta.21 => 2.2.0

build.sbt, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/data/GitHub.scala, modules/sbt-devoops-github-core/src/test/scala/kevinlee/github/data/GitHubSpec.scala, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubPlugin.scala, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpClient.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpRequest.scala, modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala, project/build.properties
Close #401 - Upgrade effectie and logger-f to 2.0.0-beta4 and update the code accordingly / also upgrade other libraries
- effectie 2.0.0-beta2 => 2.0.0-beta4
- logger-f 2.0.0-beta2 => 2.0.0-beta4
- sbt 1.8.0-RC1 => 1.8.0
- hedgehog 0.9.0 => 0.10.1
- cats 2.8.0 => 2.9.0
- cats-effect 3.3.14 => 3.4.3
- extras 0.20.0 => 0.26.0
- just-semver 0.5.0 => 0.6.0
- sbt-scalafmt 2.4.6 => 2.5.0
- sbt-scalafix 0.10.3 => 0.10.4
=> Close #401 - Upgrade effectie and logger-f to 2.0.0-beta4 and update the code accordingly / also upgrade other libraries

.scalafmt.conf, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/data/GitHub.scala, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpClient.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpRequest.scala, modules/sbt-devoops-java/src/main/scala/devoops/DevOopsJavaPlugin.scala, modules/sbt-devoops-release-version-policy/src/main/scala/devoops/DevOopsReleaseVersionPolicyPlugin.scala, modules/sbt-devoops-sbt-extra/src/main/scala/devoops/DevOopsSbtExtraPlugin.scala, modules/sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala, modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala
Bump scalafmt to 3.7.17 and reformat the code
=> Bump scalafmt to 3.7.17 and reformat the code

modules/sbt-devoops-common/src/test/scala/kevinlee/Gens.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/git/Git.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/GitHubApi.scala, modules/sbt-devoops-github-core/src/main/scala/kevinlee/github/data/GitHubError.scala, modules/sbt-devoops-github/src/main/scala/devoops/DevOopsGitHubReleasePlugin.scala, modules/sbt-devoops-github/src/main/scala/devoops/data/SbtTask.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpRequest.scala, modules/sbt-devoops-http-core/src/main/scala/kevinlee/http/HttpResponse.scala, modules/sbt-devoops-starter/src/main/scala/devoops/DevOopsStarterPlugin.scala, project/plugins.sbt
=> Use sbt-tpolecat

build.sbt
Update: build.sbt - replace `final val` with `val`
=> Update: build.sbt - replace `final val` with `val`

project/plugins.sbt
Upgrade sbt plugins
* sbt-docusaur to `0.15.0`
* sbt-devoops to `3.0.0`
=> Upgrade sbt plugins

modules/sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #437 - Update `kind-projector` version for new Scala `2.13`, `2.12` and `2.11`
=> Close #437 - Update `kind-projector` version for new Scala `2.13`, `2.12` and `2.11`

modules/sbt-devoops-scala/src/main/scala/devoops/DevOopsScalaPlugin.scala
Close #441 - [`sbt-devoops-scala`] Add `-Ymacro-annotations` to `scalacOptions` for Scala `2.13.3` and higher
=> Close #441 - [`sbt-devoops-scala`] Add `-Ymacro-annotations` to `scalacOptions` for Scala `2.13.3` and higher

project/plugins.sbt
Bump `sbt-docusaur` and `sbt-devoops`
* `sbt-docusaur` to `0.16.0`
* `sbt-devoops` to `3.1.0`
=> Bump `sbt-docusaur` and `sbt-devoops`

website/docs/getting-started.md, website/docs/gh-release-plugin/examples.md, website/docusaurus.config.js, website/src/pages/versions.js
=> Update docs: new version info

build.sbt
Close #454 - Bump `sbt-version-policy` to `3.2.1`
=> Close #454 - Bump sbt-version-policy to 3.2.1

project/build.properties
=> Upgrade sbt to 1.10.7

modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-2-test/project/build.properties, modules/sbt-devoops-scala/src/sbt-test/sbt-devoops-scala/scala-3-test/project/build.properties
Update sbt version in sbt-test to 1.11.2
=> Update sbt version in sbt-test to 1.11.2
